default :
  Input :
    Discovery dataset name : "TCGA_Discovery"
    Expression matrix : "example_data/TCGA.no.dup.log2.norm.1078set.txt"
    #Possible values: "RNA-seq", "Affymetrix", "Other"
    Expression type : "Other"
    #Possible values: "Carcinoma_Fractions", "Lymphoma_Fractions" or a path to a file containing the precomputed cell fractions
    Cell type fractions : "Carcinoma_Fractions"
    Annotation file : "example_data/TCGA.no.dup.log2.norm.1078set.annotation"
    Annotation file column to scale by : "Histology"
    Annotation file column(s) to plot : ["Histology", "Tissue"]
    CIBERSORTx username : "xin.li4@nih.gov"
    CIBERSORTx token : "22cc06bc9276fe959dad8b689bc050c9"

  Output :
    Output folder : "DiscoveryOutput_TCGA"

  Pipeline settings :
    #Pipeline steps:
    #   step 1 (cell type fraction estimation)
    #   step 2 (cell type expression purification)
    #   step 3 (cell state discovery)
    #   step 4 (choosing the number of cell states)
    #   step 5 (extracting cell state information)
    #   step 6 (cell state QC filter)
    #   step 7 (advanced cell state QC filter)
    #   step 8 (ecotype discovery)
    Pipeline steps to skip : [1,2,3,7,] # Step 7 is skipped by default
    Number of threads : 10    
    Number of NMF restarts : 5
    Maximum number of states per cell type : 20
    Cophenetic coefficient cutoff : 0.95
    CIBERSORTx fractions Singularity path : NULL
    CIBERSORTx hires Singularity path : NULL
    Minimum number of states in ecotypes : 3
    



